mongo:
  db: 'remit'
  # @todo: mettere l'host pc olanda
  #  adress: 'WPWS07133656'
  adress: '127.0.0.1'
  ip: '27017'
  # log_level: ::Logger::FATAL
  log_level: ::Logger::INFO
path:
  download: './excel_file/download/' 
url:
  site: 'http://www.terna.it/it-it/sistemaelettrico/transparencyreport/transmissionandinterconnection/plannedoutages.aspx'

 
