defaults: &defaults
  database:
    name: 'transmission'
    adress: '127.0.0.1'
    port: '27018'
    log_level: "::Logger::INFO"
  path:
    download: './excel_file/download/'
  url:
    site: 'http://www.terna.it/it-it/sistemaelettrico/transparencyreport/transmissionandinterconnection/plannedoutages.aspx' 

development:
  <<: *defaults
  altro: 800

test:
  <<: *defaults

production:
  <<: *defaults


 
