defaults: &defaults
  url:
    site: 'http://www.terna.it/it-it/sistemaelettrico/transparencyreport/transmissionandinterconnection/plannedoutages.aspx' 

  mail:
    from: 'michele.boscolo@eni.com'
    to: 'michele.boscolo@eni.com'
    server: 'relay.eni.pri'
    port: 25

development:
  <<: *defaults
  database:
    name: 'Ampere'
    adress: '127.0.0.1:27030'
    log_level: "::Logger::INFO"

  path:
    download: './excel_file/'
    archivio: './excel_file/Archivio/'
    match:    './excel_file/Match/'
    nomatch:  './excel_file/NoMatch/'
    sync:     './excel_file_dev'

test:
  <<: *defaults

production:
  <<: *defaults
  database:
    name: 'Ampere'
    adress1: '10.130.96.220:27018'
    adress2: '10.130.96.220:27019'
    adress3: '10.130.96.144:27018'
    log_level: "::Logger::INFO"
  path:
    download: './excel_file/'
    archivio: './excel_file/Archivio/'
    match:    './excel_file/Match/'
    nomatch:  './excel_file/NoMatch/'
    sync: '//ennf1002/unitagp/MEOR/QLIKVIEW/05b REPORT MAPPA ITALIA/remit_terna'

